
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'CA5498D0A57746F568F755347B2AB9D9'
    
_lr_action_items = {'QUOTE':([0,1,2,3,4,8,9,10,12,13,15,16,17,18,],[1,1,-7,-8,-6,-1,13,1,-9,-4,1,-3,-2,-5,]),'$end':([0,2,3,4,7,8,12,13,15,16,17,18,],[-9,-7,-8,-6,0,-1,-9,-4,-9,-3,-2,-5,]),'NUM':([0,1,6,10,12,15,],[2,2,2,2,2,2,]),'LPAREN':([5,],[10,]),'TEXT':([0,1,6,10,12,15,],[3,3,3,3,3,3,]),'RPAREN':([2,3,4,8,10,12,13,14,15,16,17,18,],[-7,-8,-6,-1,-9,-9,-4,17,-9,-3,-2,-5,]),'SIMB':([0,1,2,3,4,6,10,11,12,15,],[4,4,-7,-8,-6,4,4,15,4,4,]),'BSLASH':([0,1,10,15,],[5,5,5,5,]),'LET':([0,1,10,15,],[6,6,6,6,]),'PLUS':([0,1,2,3,4,8,10,15,],[-9,-9,-7,-8,-6,12,-9,-9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'exp':([0,1,10,15,],[7,9,14,18,]),'atom':([0,1,6,10,12,15,],[8,8,11,8,16,8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> exp","S'",1,None,None,None),
  ('exp -> atom','exp',1,'p_exp_atom','yaccS.py',64),
  ('exp -> BSLASH LPAREN exp RPAREN','exp',4,'p_exp_wrap','yaccS.py',68),
  ('exp -> atom PLUS atom','exp',3,'p_exp','yaccS.py',73),
  ('exp -> QUOTE exp QUOTE','exp',3,'p_exp_string','yaccS.py',78),
  ('exp -> LET atom SIMB exp','exp',4,'p_exp_let','yaccS.py',83),
  ('atom -> SIMB','atom',1,'p_atom_simbol','yaccS.py',88),
  ('atom -> NUM','atom',1,'p_atom_num','yaccS.py',92),
  ('atom -> TEXT','atom',1,'p_atom_word','yaccS.py',96),
  ('atom -> <empty>','atom',0,'p_atom_empty','yaccS.py',100),
]
